### ISSUE TITLE
build_docs.py script fails with configuration error

### ISSUE THREAD

**Issue by SCalwas** [awsdocs/aws-toolkit-visual-studio-user-guide#5]
Run the build_docs.py script with Python 3.7.1 and Sphinx 1.8.2.
Fails with the message "Configuration error: There is a programmable error in your configuration file: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 2283: invalid start byte

**Comment by Paul-B-AWS** [comment]
This is no longer relevant since the environment has been converted.
